// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKLFS6Ey9GT78TRulxKwMmsswrY2D2egI',
    appId: '1:1015490257159:web:9b437ebb6e550d8af8e5a2',
    messagingSenderId: '1015490257159',
    projectId: 'ecomm-online',
    authDomain: 'ecomm-online.firebaseapp.com',
    storageBucket: 'ecomm-online.firebasestorage.app',
    measurementId: 'G-TK5EWVP5QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB23U-DJfJp92wjSak3i6q9vLsObJKtDh0',
    appId: '1:1015490257159:android:9c767e919e702e15f8e5a2',
    messagingSenderId: '1015490257159',
    projectId: 'ecomm-online',
    storageBucket: 'ecomm-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRmQtInT6ZvnWzwrkrvPc41i8q3bAy8-w',
    appId: '1:1015490257159:ios:1fc65e8029f41957f8e5a2',
    messagingSenderId: '1015490257159',
    projectId: 'ecomm-online',
    storageBucket: 'ecomm-online.firebasestorage.app',
    iosBundleId: 'com.example.appDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRmQtInT6ZvnWzwrkrvPc41i8q3bAy8-w',
    appId: '1:1015490257159:ios:1fc65e8029f41957f8e5a2',
    messagingSenderId: '1015490257159',
    projectId: 'ecomm-online',
    storageBucket: 'ecomm-online.firebasestorage.app',
    iosBundleId: 'com.example.appDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKLFS6Ey9GT78TRulxKwMmsswrY2D2egI',
    appId: '1:1015490257159:web:9bca4d336c689827f8e5a2',
    messagingSenderId: '1015490257159',
    projectId: 'ecomm-online',
    authDomain: 'ecomm-online.firebaseapp.com',
    storageBucket: 'ecomm-online.firebasestorage.app',
    measurementId: 'G-H07R4VJC00',
  );
}
